version: '3'
services:

  foos-app:
    image: foos-app:latest
    restart: on-failure
    ports:
      - 3000:3000
    links:
      - foos-db
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
    volumes:
      - /usr/share/zoneinfo/America/Denver:/etc/localtime:ro

  foos-db:
    image: mangoraft/mongodb-arm
    restart: always
    environment:
      - AUTH=no
    ports:
      - 27017:27017
      - 28017:28017
    volumes:
      - /var/lib/mongodb:/data/db:rw
      - /usr/share/zoneinfo/America/Denver:/etc/localtime:ro

  portainer:
    image: portainer/portainer
    restart: on-failure
    environment:
      - TZ=America/Denver
    ports:
      - 8091:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    # command:
    #   - -H
    #   - unix:///var/run/docker.sock
    # deploy:
    #   placement:
    #     constraints:
    #       - node.role == manager
